name: Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate version.txt
        run: |
          REQUIRED_VERSION="version=1.0.0-release01"
          ACTUAL_VERSION=$(cat version.txt | tr -d ' \t\n\r')
          if [ "$ACTUAL_VERSION" != "$REQUIRED_VERSION" ]; then
            echo "ERROR: version.txt mismatch! Expected: $REQUIRED_VERSION, Found: $ACTUAL_VERSION"
            exit 1
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ZORGLUB_VERSION=${{ steps.get_version.outputs.version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/zorglub-ai:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/zorglub-ai:latest
      - name: Get version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt | tr -d ' \t\n\r')
          VERSION=${VERSION#version=}
          echo "version=$VERSION" >> $GITHUB_OUTPUT